version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8876:80"
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        container_name: project_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: project_app

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: lardocker2
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: project_db

    app_test: # Новый контейнер для тестирования
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        environment:
            APP_ENV: testing
            DB_DATABASE: lardocker2_testing # Новая база данных для тестов
        depends_on:
            - db
        container_name: project_app_test # Уникальное имя для контейнера тестирования

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: project_phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8082:80"
        depends_on:
            - db

volumes:
    db-data:
